apiVersion: v1
kind: Service
metadata:
  name: hello-svc-v1
  namespace: hello
spec:
  selector:
    app: hello-app-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
