apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook-vs
  namespace: book
spec:
  hosts:
  - "*"
  gateways:
  - guestbook-gateway
  http:
  - match:
    - uri:
        exact: "/home"
    redirect:
      uri: "/"
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: guestbook-ui
        port:
          number: 80
